/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ServersRouteImport } from './routes/servers'
import { Route as VerifyRouteImport } from './routes/verify'
import { Route as DashboardGuildIdRouteImport } from './routes/dashboard/$guildId'
import { Route as ApiAuthLocalLoginRouteImport } from './routes/api/auth/local-login'
import { Route as ApiAuthLogoutRouteImport } from './routes/api/auth/logout'
import { Route as ApiVerifyConfirmRouteImport } from './routes/api/verify/confirm'
import { Route as ApiVerifyRequestEmailRouteImport } from './routes/api/verify/request-email'
import { Route as ApiAuthPasskeyOptionsRouteImport } from './routes/api/auth/passkey/options'
import { Route as ApiAuthPasskeyRegisterOptionsRouteImport } from './routes/api/auth/passkey/register-options'
import { Route as ApiAuthPasskeyRegisterVerifyRouteImport } from './routes/api/auth/passkey/register-verify'
import { Route as ApiAuthPasskeyVerifyRouteImport } from './routes/api/auth/passkey/verify'
import { Route as ApiPublicBotSyncRouteImport } from './routes/api/public/bot/sync'
import { Route as ApiPublicVerifyStartRouteImport } from './routes/api/public/verify/start'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ServersRoute = ServersRouteImport.update({
  id: '/servers',
  path: '/servers',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyRoute = VerifyRouteImport.update({
  id: '/verify',
  path: '/verify',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardGuildIdRoute = DashboardGuildIdRouteImport.update({
  id: '/dashboard/$guildId',
  path: '/dashboard/$guildId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthLocalLoginRoute = ApiAuthLocalLoginRouteImport.update({
  id: '/api/auth/local-login',
  path: '/api/auth/local-login',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthLogoutRoute = ApiAuthLogoutRouteImport.update({
  id: '/api/auth/logout',
  path: '/api/auth/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiVerifyConfirmRoute = ApiVerifyConfirmRouteImport.update({
  id: '/api/verify/confirm',
  path: '/api/verify/confirm',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiVerifyRequestEmailRoute = ApiVerifyRequestEmailRouteImport.update({
  id: '/api/verify/request-email',
  path: '/api/verify/request-email',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthPasskeyOptionsRoute = ApiAuthPasskeyOptionsRouteImport.update({
  id: '/api/auth/passkey/options',
  path: '/api/auth/passkey/options',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthPasskeyRegisterOptionsRoute =
  ApiAuthPasskeyRegisterOptionsRouteImport.update({
    id: '/api/auth/passkey/register-options',
    path: '/api/auth/passkey/register-options',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiAuthPasskeyRegisterVerifyRoute =
  ApiAuthPasskeyRegisterVerifyRouteImport.update({
    id: '/api/auth/passkey/register-verify',
    path: '/api/auth/passkey/register-verify',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiAuthPasskeyVerifyRoute = ApiAuthPasskeyVerifyRouteImport.update({
  id: '/api/auth/passkey/verify',
  path: '/api/auth/passkey/verify',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicBotSyncRoute = ApiPublicBotSyncRouteImport.update({
  id: '/api/public/bot/sync',
  path: '/api/public/bot/sync',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicVerifyStartRoute = ApiPublicVerifyStartRouteImport.update({
  id: '/api/public/verify/start',
  path: '/api/public/verify/start',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/servers': typeof ServersRoute
  '/verify': typeof VerifyRoute
  '/dashboard/$guildId': typeof DashboardGuildIdRoute
  '/api/auth/local-login': typeof ApiAuthLocalLoginRoute
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/verify/confirm': typeof ApiVerifyConfirmRoute
  '/api/verify/request-email': typeof ApiVerifyRequestEmailRoute
  '/api/auth/passkey/options': typeof ApiAuthPasskeyOptionsRoute
  '/api/auth/passkey/register-options': typeof ApiAuthPasskeyRegisterOptionsRoute
  '/api/auth/passkey/register-verify': typeof ApiAuthPasskeyRegisterVerifyRoute
  '/api/auth/passkey/verify': typeof ApiAuthPasskeyVerifyRoute
  '/api/public/bot/sync': typeof ApiPublicBotSyncRoute
  '/api/public/verify/start': typeof ApiPublicVerifyStartRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/servers': typeof ServersRoute
  '/verify': typeof VerifyRoute
  '/dashboard/$guildId': typeof DashboardGuildIdRoute
  '/api/auth/local-login': typeof ApiAuthLocalLoginRoute
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/verify/confirm': typeof ApiVerifyConfirmRoute
  '/api/verify/request-email': typeof ApiVerifyRequestEmailRoute
  '/api/auth/passkey/options': typeof ApiAuthPasskeyOptionsRoute
  '/api/auth/passkey/register-options': typeof ApiAuthPasskeyRegisterOptionsRoute
  '/api/auth/passkey/register-verify': typeof ApiAuthPasskeyRegisterVerifyRoute
  '/api/auth/passkey/verify': typeof ApiAuthPasskeyVerifyRoute
  '/api/public/bot/sync': typeof ApiPublicBotSyncRoute
  '/api/public/verify/start': typeof ApiPublicVerifyStartRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/servers': typeof ServersRoute
  '/verify': typeof VerifyRoute
  '/dashboard/$guildId': typeof DashboardGuildIdRoute
  '/api/auth/local-login': typeof ApiAuthLocalLoginRoute
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/verify/confirm': typeof ApiVerifyConfirmRoute
  '/api/verify/request-email': typeof ApiVerifyRequestEmailRoute
  '/api/auth/passkey/options': typeof ApiAuthPasskeyOptionsRoute
  '/api/auth/passkey/register-options': typeof ApiAuthPasskeyRegisterOptionsRoute
  '/api/auth/passkey/register-verify': typeof ApiAuthPasskeyRegisterVerifyRoute
  '/api/auth/passkey/verify': typeof ApiAuthPasskeyVerifyRoute
  '/api/public/bot/sync': typeof ApiPublicBotSyncRoute
  '/api/public/verify/start': typeof ApiPublicVerifyStartRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/servers'
    | '/verify'
    | '/dashboard/$guildId'
    | '/api/auth/local-login'
    | '/api/auth/logout'
    | '/api/verify/confirm'
    | '/api/verify/request-email'
    | '/api/auth/passkey/options'
    | '/api/auth/passkey/register-options'
    | '/api/auth/passkey/register-verify'
    | '/api/auth/passkey/verify'
    | '/api/public/bot/sync'
    | '/api/public/verify/start'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/servers'
    | '/verify'
    | '/dashboard/$guildId'
    | '/api/auth/local-login'
    | '/api/auth/logout'
    | '/api/verify/confirm'
    | '/api/verify/request-email'
    | '/api/auth/passkey/options'
    | '/api/auth/passkey/register-options'
    | '/api/auth/passkey/register-verify'
    | '/api/auth/passkey/verify'
    | '/api/public/bot/sync'
    | '/api/public/verify/start'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/servers'
    | '/verify'
    | '/dashboard/$guildId'
    | '/api/auth/local-login'
    | '/api/auth/logout'
    | '/api/verify/confirm'
    | '/api/verify/request-email'
    | '/api/auth/passkey/options'
    | '/api/auth/passkey/register-options'
    | '/api/auth/passkey/register-verify'
    | '/api/auth/passkey/verify'
    | '/api/public/bot/sync'
    | '/api/public/verify/start'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  ServersRoute: typeof ServersRoute
  VerifyRoute: typeof VerifyRoute
  DashboardGuildIdRoute: typeof DashboardGuildIdRoute
  ApiAuthLocalLoginRoute: typeof ApiAuthLocalLoginRoute
  ApiAuthLogoutRoute: typeof ApiAuthLogoutRoute
  ApiVerifyConfirmRoute: typeof ApiVerifyConfirmRoute
  ApiVerifyRequestEmailRoute: typeof ApiVerifyRequestEmailRoute
  ApiAuthPasskeyOptionsRoute: typeof ApiAuthPasskeyOptionsRoute
  ApiAuthPasskeyRegisterOptionsRoute: typeof ApiAuthPasskeyRegisterOptionsRoute
  ApiAuthPasskeyRegisterVerifyRoute: typeof ApiAuthPasskeyRegisterVerifyRoute
  ApiAuthPasskeyVerifyRoute: typeof ApiAuthPasskeyVerifyRoute
  ApiPublicBotSyncRoute: typeof ApiPublicBotSyncRoute
  ApiPublicVerifyStartRoute: typeof ApiPublicVerifyStartRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/servers': {
      id: '/servers'
      path: '/servers'
      fullPath: '/servers'
      preLoaderRoute: typeof ServersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify': {
      id: '/verify'
      path: '/verify'
      fullPath: '/verify'
      preLoaderRoute: typeof VerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/$guildId': {
      id: '/dashboard/$guildId'
      path: '/dashboard/$guildId'
      fullPath: '/dashboard/$guildId'
      preLoaderRoute: typeof DashboardGuildIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/local-login': {
      id: '/api/auth/local-login'
      path: '/api/auth/local-login'
      fullPath: '/api/auth/local-login'
      preLoaderRoute: typeof ApiAuthLocalLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/logout': {
      id: '/api/auth/logout'
      path: '/api/auth/logout'
      fullPath: '/api/auth/logout'
      preLoaderRoute: typeof ApiAuthLogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/verify/confirm': {
      id: '/api/verify/confirm'
      path: '/api/verify/confirm'
      fullPath: '/api/verify/confirm'
      preLoaderRoute: typeof ApiVerifyConfirmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/verify/request-email': {
      id: '/api/verify/request-email'
      path: '/api/verify/request-email'
      fullPath: '/api/verify/request-email'
      preLoaderRoute: typeof ApiVerifyRequestEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/passkey/options': {
      id: '/api/auth/passkey/options'
      path: '/api/auth/passkey/options'
      fullPath: '/api/auth/passkey/options'
      preLoaderRoute: typeof ApiAuthPasskeyOptionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/passkey/register-options': {
      id: '/api/auth/passkey/register-options'
      path: '/api/auth/passkey/register-options'
      fullPath: '/api/auth/passkey/register-options'
      preLoaderRoute: typeof ApiAuthPasskeyRegisterOptionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/passkey/register-verify': {
      id: '/api/auth/passkey/register-verify'
      path: '/api/auth/passkey/register-verify'
      fullPath: '/api/auth/passkey/register-verify'
      preLoaderRoute: typeof ApiAuthPasskeyRegisterVerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/passkey/verify': {
      id: '/api/auth/passkey/verify'
      path: '/api/auth/passkey/verify'
      fullPath: '/api/auth/passkey/verify'
      preLoaderRoute: typeof ApiAuthPasskeyVerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/bot/sync': {
      id: '/api/public/bot/sync'
      path: '/api/public/bot/sync'
      fullPath: '/api/public/bot/sync'
      preLoaderRoute: typeof ApiPublicBotSyncRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/verify/start': {
      id: '/api/public/verify/start'
      path: '/api/public/verify/start'
      fullPath: '/api/public/verify/start'
      preLoaderRoute: typeof ApiPublicVerifyStartRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  ServersRoute: ServersRoute,
  VerifyRoute: VerifyRoute,
  DashboardGuildIdRoute: DashboardGuildIdRoute,
  ApiAuthLocalLoginRoute: ApiAuthLocalLoginRoute,
  ApiAuthLogoutRoute: ApiAuthLogoutRoute,
  ApiVerifyConfirmRoute: ApiVerifyConfirmRoute,
  ApiVerifyRequestEmailRoute: ApiVerifyRequestEmailRoute,
  ApiAuthPasskeyOptionsRoute: ApiAuthPasskeyOptionsRoute,
  ApiAuthPasskeyRegisterOptionsRoute: ApiAuthPasskeyRegisterOptionsRoute,
  ApiAuthPasskeyRegisterVerifyRoute: ApiAuthPasskeyRegisterVerifyRoute,
  ApiAuthPasskeyVerifyRoute: ApiAuthPasskeyVerifyRoute,
  ApiPublicBotSyncRoute: ApiPublicBotSyncRoute,
  ApiPublicVerifyStartRoute: ApiPublicVerifyStartRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
