/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ServersRouteImport } from './routes/servers'
import { Route as DashboardGuildIdRouteImport } from './routes/dashboard/$guildId'
import { Route as ApiAuthLogoutRouteImport } from './routes/api/auth/logout'
import { Route as ApiAuthDiscordOauthCallbackRouteImport } from './routes/api/auth/discord/oauth-callback'
import { Route as ApiAuthDiscordLoginRouteImport } from './routes/api/auth/discord/login'
import { Route as ApiPublicBotSyncRouteImport } from './routes/api/public/bot/sync'

const IndexRoute = IndexRouteImport.update({
  id: '/', path: '/', getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login', path: '/login', getParentRoute: () => rootRouteImport,
} as any)
const ServersRoute = ServersRouteImport.update({
  id: '/servers', path: '/servers', getParentRoute: () => rootRouteImport,
} as any)
const DashboardGuildIdRoute = DashboardGuildIdRouteImport.update({
  id: '/dashboard/$guildId', path: '/dashboard/$guildId', getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthLogoutRoute = ApiAuthLogoutRouteImport.update({
  id: '/api/auth/logout', path: '/api/auth/logout', getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthDiscordOauthCallbackRoute = ApiAuthDiscordOauthCallbackRouteImport.update({
  id: '/api/auth/discord/oauth-callback', path: '/api/auth/discord/oauth-callback', getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthDiscordLoginRoute = ApiAuthDiscordLoginRouteImport.update({
  id: '/api/auth/discord/login', path: '/api/auth/discord/login', getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicBotSyncRoute = ApiPublicBotSyncRouteImport.update({
  id: '/api/public/bot/sync', path: '/api/public/bot/sync', getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/servers': typeof ServersRoute
  '/dashboard/$guildId': typeof DashboardGuildIdRoute
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/auth/discord/oauth-callback': typeof ApiAuthDiscordOauthCallbackRoute
  '/api/auth/discord/login': typeof ApiAuthDiscordLoginRoute
  '/api/public/bot/sync': typeof ApiPublicBotSyncRoute
}
export interface FileRoutesByTo extends FileRoutesByFullPath {}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/servers': typeof ServersRoute
  '/dashboard/$guildId': typeof DashboardGuildIdRoute
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/auth/discord/oauth-callback': typeof ApiAuthDiscordOauthCallbackRoute
  '/api/auth/discord/login': typeof ApiAuthDiscordLoginRoute
  '/api/public/bot/sync': typeof ApiPublicBotSyncRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: keyof FileRoutesByFullPath
  fileRoutesByTo: FileRoutesByTo
  to: keyof FileRoutesByTo
  id: keyof FileRoutesById
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  ServersRoute: typeof ServersRoute
  DashboardGuildIdRoute: typeof DashboardGuildIdRoute
  ApiAuthLogoutRoute: typeof ApiAuthLogoutRoute
  ApiAuthDiscordOauthCallbackRoute: typeof ApiAuthDiscordOauthCallbackRoute
  ApiAuthDiscordLoginRoute: typeof ApiAuthDiscordLoginRoute
  ApiPublicBotSyncRoute: typeof ApiPublicBotSyncRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': { id: '/'; path: '/'; fullPath: '/'; preLoaderRoute: typeof IndexRouteImport; parentRoute: typeof rootRouteImport }
    '/login': { id: '/login'; path: '/login'; fullPath: '/login'; preLoaderRoute: typeof LoginRouteImport; parentRoute: typeof rootRouteImport }
    '/servers': { id: '/servers'; path: '/servers'; fullPath: '/servers'; preLoaderRoute: typeof ServersRouteImport; parentRoute: typeof rootRouteImport }
    '/dashboard/$guildId': { id: '/dashboard/$guildId'; path: '/dashboard/$guildId'; fullPath: '/dashboard/$guildId'; preLoaderRoute: typeof DashboardGuildIdRouteImport; parentRoute: typeof rootRouteImport }
    '/api/auth/logout': { id: '/api/auth/logout'; path: '/api/auth/logout'; fullPath: '/api/auth/logout'; preLoaderRoute: typeof ApiAuthLogoutRouteImport; parentRoute: typeof rootRouteImport }
    '/api/auth/discord/oauth-callback': { id: '/api/auth/discord/oauth-callback'; path: '/api/auth/discord/oauth-callback'; fullPath: '/api/auth/discord/oauth-callback'; preLoaderRoute: typeof ApiAuthDiscordOauthCallbackRouteImport; parentRoute: typeof rootRouteImport }
    '/api/auth/discord/login': { id: '/api/auth/discord/login'; path: '/api/auth/discord/login'; fullPath: '/api/auth/discord/login'; preLoaderRoute: typeof ApiAuthDiscordLoginRouteImport; parentRoute: typeof rootRouteImport }
    '/api/public/bot/sync': { id: '/api/public/bot/sync'; path: '/api/public/bot/sync'; fullPath: '/api/public/bot/sync'; preLoaderRoute: typeof ApiPublicBotSyncRouteImport; parentRoute: typeof rootRouteImport }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute,
  LoginRoute,
  ServersRoute,
  DashboardGuildIdRoute,
  ApiAuthLogoutRoute,
  ApiAuthDiscordOauthCallbackRoute,
  ApiAuthDiscordLoginRoute,
  ApiPublicBotSyncRoute,
}

export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
